apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: stocksvision-cert
spec:
  secretName: stocksvision-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: stocks.vision
  dnsNames:
  - stocks.vision
  - '*.stocks.vision'