apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stocksvision
  labels:
    app: stocksvision
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stocksvision
    spec:
      containers:
#              
        - name: webui
          image: kristianwindsor/stocksvision-webui
          env:
            - name: API_URL
              value: https://api.stocks.vision
          ports:
            - containerPort: 80
#              
        - name: backend
          image: kristianwindsor/stocksvision-backend
          env:
            - name: MYSQL_HOSTNAME
              value: localhost
          ports:
            - containerPort: 5000
#              
        - name: mysql
          image: kristianwindsor/stocksvision-mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pass
          volumeMounts:
           - name: stocksvision-mysql
             mountPath: /var/lib/mysql
#            
        - name: crawlapi
          image: kristianwindsor/stocksvision-crawlapi
          ports:
            - containerPort: 8083
          env:
            - name: MYSQL_HOSTNAME
              value: localhost
            - name: REDDIT_USERNAME
              value: '84935'
            - name: REDDIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stocksvision-env
                  key: reddit-password
            - name: REDDIT_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: stocksvision-env
                  key: reddit-clientid
            - name: REDDIT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stocksvision-env
                  key: reddit-secret
#    
        - name: crawlscheduler
          image: kristianwindsor/stocksvision-crawlscheduler
          env:
            - name: CRAWLAPI_HOSTNAME
              value: localhost
            - name: MYSQL_HOSTNAME
              value: localhost
#           
        - name: phpmyadmin
          image: kristianwindsor/stocksvision-phpmyadmin
          ports:
            - containerPort: 8080
              name: phpmyadmin
          env:
            - name: PMA_HOST
              value: 127.0.0.1
#
      imagePullSecrets:
        - name: dockerhub
      volumes:
       - name: stocksvision-mysql
         persistentVolumeClaim:
           claimName: stocksvision-mysql
