version: "3.7"
services:
#
  mysql:
    image: kristianwindsor/stocksvision-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
#
  webui:
    image: kristianwindsor/stocksvision-webui
    environment:
      - API_URL=http://localhost:5000
    ports:
      - 80:80
    volumes:
      - ./webui/src:/var/www/html/
#
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=phpmyadmin
      - PMA_PASSWORD=pass
    ports:
      - 8080:80
#
  backend:
    image: kristianwindsor/stocksvision-backend
    environment:
      - MYSQL_HOSTNAME=mysql
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/
#
  crawlapi:
    image: kristianwindsor/stocksvision-crawlapi
    environment:
      - MYSQL_HOSTNAME=mysql
    ports:
      - 5001:5001
    volumes:
      - ./crawlapi/src/:/app/
    env_file:
      - environment.env
#
  crawlscheduler:
    image: kristianwindsor/stocksvision-crawlscheduler
    environment:
      - MYSQL_HOSTNAME=mysql
      - CRAWLAPI_HOSTNAME=crawlapi
    volumes:
      - ./crawlscheduler/src/:/app/