version: "3.7"
services:
#
  webui:
    build: webui
    environment:
      - API_URL=http://localhost:5000
    ports:
      - 80:80
    volumes:
      - ./webui/src:/var/www/html/
    restart: always
#
  backend:
    build: backend
    environment:
      - MYSQL_HOSTNAME=mysql
      - CRAWLER_URL=http://crawler:5001
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/
    restart: always
#
  mysql:
    build: mysql/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    restart: always
#
  crawler:
    build: crawler
    environment:
      - MYSQL_HOSTNAME=mysql
    ports:
      - 5001:5001
    volumes:
      - ./crawler/src/:/app/
    env_file:
      - environment.env
    restart: always
#
  crawlscheduler:
    build: crawlscheduler
    environment:
      - MYSQL_HOSTNAME=mysql
      - CRAWLER_URL=http://crawler:5002
    volumes:
      - ./crawlscheduler/src/:/app/
#
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=phpmyadmin
      - PMA_PASSWORD=pass
    ports:
      - 8080:80
    restart: always
