version: "3"
services:
  db:
    image: kristianwindsor/stocksvision-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    tty: true
    stdin_open: true
  webui:
    image: kristianwindsor/stocksvision-webui
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./webui/src:/usr/local/apache2/htdocs/
    tty: true
    stdin_open: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_USER=phpmyadmin
      - PMA_PASSWORD=pass
    restart: always
    tty: true
    stdin_open: true
  backend:
    image: kristianwindsor/stocksvision-backend
    ports:
      - 8082:5000
    restart: always
    volumes:
      - ./backend/src/:/app/
    tty: true
    stdin_open: true
  crawlapi:
    image: kristianwindsor/stocksvision-crawlapi
    environment:
      - MYSQL_HOSTNAME=db
    ports:
      - 8083:8083
    restart: always
    volumes:
      - ./crawlapi/src/:/app/
    tty: true
    stdin_open: true
  crawlscheduler:
    image: kristianwindsor/stocksvision-crawlscheduler
    environment:
      - CRAWLAPI_HOSTNAME=crawlapi
    restart: always
    volumes:
      - ./crawlscheduler/src/:/app/
    tty: true
    stdin_open: true
