version: "3.7"
services:
#
  webui:
    build: webui
    environment:
      - API_URL=http://localhost:5000
    ports:
      - 80:80
    volumes:
      - ./webui/src:/var/www/html/
    restart: always
#
  backend:
    build: backend
    environment:
      - MYSQL_HOSTNAME=db
      - CRAWLER_URL=http://crawler:5001
      - USE_GUNICORN=false
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/
    restart: always
#
  db:
    build: db/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    restart: always
#
  crawler:
    build: crawler
    environment:
      - MYSQL_HOSTNAME=db
    ports:
      - 5001:5001
    volumes:
      - ./crawler/src/:/app/
    env_file:
      - environment.env
    restart: always
#
  crawlscheduler:
    build: crawlscheduler
    environment:
      - MYSQL_HOSTNAME=db
      - CRAWLER_URL=http://crawler:5002
    volumes:
      - ./crawlscheduler/src/:/app/