apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stocksvision-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: stocks.vision
    http:
      paths:
      - path: /
        backend:
          serviceName: stocksvision
          servicePort: 80
  - host: backend.stocks.vision
    http:
      paths:
      - path: /
        backend:
          serviceName: stocksvision
          servicePort: 5000
  - host: crawler.stocks.vision
    http:
      paths:
      - path: /
        backend:
          serviceName: stocksvision
          servicePort: 5001
  - host: phpmyadmin.stocks.vision
    http:
      paths:
      - path: /
        backend:
          serviceName: stocksvision
          servicePort: 8080
  tls:
  - secretName: stocksvision-cert
    hosts:
    - stocks.vision
    - '*.stocks.vision'