apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stocksvision-mysql
  labels:
    app: stocksvision
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi