# Generated by Django 2.1.5 on 2019-06-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dispensaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmid1', models.CharField(default='', max_length=200)),
                ('wmid2', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=200)),
                ('zip_code', models.CharField(default='', max_length=20)),
                ('latitude', models.CharField(default='', max_length=200)),
                ('longitude', models.CharField(default='', max_length=200)),
                ('time_zone', models.CharField(default='', max_length=200)),
                ('img_url', models.CharField(default='', max_length=200)),
                ('hours', models.CharField(default='', max_length=200)),
                ('license_type', models.CharField(default='', max_length=200)),
                ('website_url', models.CharField(default='', max_length=200)),
                ('flagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmid', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('price_g', models.CharField(default='', max_length=200)),
                ('price_eighth', models.CharField(default='', max_length=200)),
                ('price_fourth', models.CharField(default='', max_length=200)),
                ('price_half', models.CharField(default='', max_length=200)),
                ('price_oz', models.CharField(default='', max_length=200)),
                ('img_url', models.CharField(default='', max_length=200)),
                ('flagged', models.BooleanField(default=False)),
            ],
        ),
    ]
