name: Build and Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - name: Checkout
        uses: actions/checkout@v2
      # buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # dockerhub auth
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: kristianwindsor
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # build and push docker images
      - name: WebUI
        id: docker_build_webui
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kristianwindsor/stocksvision-webui:b${{ github.run_number }}
          context: ./webui/
      - name: Backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kristianwindsor/stocksvision-backend:b${{ github.run_number }}
          context: ./backend/
      - name: Crawler
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kristianwindsor/stocksvision-crawler:b${{ github.run_number }}
          context: ./crawler/
      - name: Database
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kristianwindsor/stocksvision-db:b${{ github.run_number }}
          context: ./db/
      # deploy
      - name: Sed
        run: |
            sed -i "s/kristianwindsor\\/stocksvision-backend.*/kristianwindsor\\/stocksvision-backend:b${{ github.run_number }}/" deployment.yaml
            sed -i "s/kristianwindsor\\/stocksvision-crawler.*/kristianwindsor\\/stocksvision-crawler:b${{ github.run_number }}/" deployment.yaml
            sed -i "s/kristianwindsor\\/stocksvision-webui.*/kristianwindsor\\/stocksvision-webui:b${{ github.run_number }}/" deployment.yaml
      - name: Deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f deployment.yaml
      - name: Verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout status deployment/stocksvision